# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)-$(Rev:r)
# name modifies the Build.BuildNumber format used in tag
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml

trigger:
- master

variables:

 # Container registry service connection established during pipeline creation
  dockerfilePath: '**/docker/carts/Dockerfile'
  tag: '$(Build.BuildNumber)'
  serviceName: carts

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: microservicesdemo
      type: github
      name: northpoint/microservices-demo
      endpoint: github-svcconn

stages:
  
- stage: HelmDeploy
  displayName: Helm Deploy
  jobs:
  - template: /pipeline-templates/helm-deploy-pipeline.yaml@microservicesdemo
    parameters:
      serviceName: $(serviceName)
      image: $(serviceName):$(tag)
