apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: carts 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: carts 
    spec:
      containers:
        - name: carts 
          image: kubeinnovationacr.azurecr.io/carts
          ports:
          - containerPort: 80